import Head from "next/head";
import Navbar from "@/components/Navbar";
import Experience from "@/components/Experience";
import Hero from "@/components/Hero";
import Services from "@/components/Services";
import Work from "@/components/Work";
import Quote from "@/components/Quote";
import Testmonials from "@/components/Testmonials";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Blogs from "@/components/Blogs";
export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Plumbing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="border-b">
        <Header />
        <Navbar />
      </header>
      <main className="">
        <Hero />
        <Experience />
        <Services />
        <Work />
        <Quote />
        <Testmonials />
        <Blogs />
        <Footer />
      </main>
    </>
  );
}
